/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   event_mgmt.c                                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: uxmancis <uxmancis@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/01/03 17:34:46 by uxmancis          #+#    #+#             */
/*   Updated: 2024/01/04 18:44:45 by uxmancis         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "includes/fract-ol.h"

/* mouse_event_mgmt:
*		Input: keycode generated by mlx_mouse_hook.
*		
*		Works as an index for mouse-related events.
*		Depending on the keycode (event identifier) received, 
*		mouse_event_mgmt will decide how the program should act
*		by calling to a function or to another.
*	
*		Managed events: 
*			4 : MOUSE_WHEEL_UP
*			5 : MOUSE_WHEEL_DOWN
*/
int	mouse_event_mgmt(int keycode)
{
	printf("MOUSE event detected: %d", keycode);
	if (keycode == MOUSE_WHEEL_UP)
		printf("MOUSE WHEEL UP\n");
	if (keycode == MOUSE_WHEEL_DOWN)
		printf("MOUSE WHEEL down\n");
	return (0);
}

/* key_event_mgmt:
*		Input: keycode generated by mlx_mouse_hook.
*		
*		Works as an index for keyboard-related events.
*		Depending on the keycode (event identifier) received, 
*		key_event_mgmt will decide how the program should act
*		by calling to a function or to another.
*	
*		Managed events: 
*			4 : MOUSE_WHEEL_UP
*			5 : MOUSE_WHEEL_DOWN
*/
int	key_event_mgmt(int keycode)
{
	printf("KEY event detected: %d", keycode);
	if (keycode == ESC)
		printf("ESC\n");
	if (keycode == CLOSE)
		printf("CLOSE\n");
	return (0);
}
