/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   event_mgmt.c                                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: uxmancis <uxmancis@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/01/03 17:34:46 by uxmancis          #+#    #+#             */
/*   Updated: 2024/01/09 21:34:55 by uxmancis         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "includes/fract-ol.h"

/* ft_zoom:
*		Uses zoom multiplier to adjust complex number maximum and
*		minum values.
*		Then, the fractal is generated again at a different 
*		resolution, giving the appearance of zooming in or out.
*/
void	ft_zoom(t_data *all, double zoom_nb)
{
	double	center_x;
	double	center_y;
	
	center_x = all->x_min - all->x_max; //real part | Center of complex numbers. Where is 0,0?
	center_y = all->y_max - all->y_min; //imaginary part | Center of complex numbers. Where is 0,0?
	all->x_max = all->x_max + (center_x - zoom_nb*center_x) / 2;
	all->x_min = all->x_max + zoom_nb*center_x;
	all->y_min = all->y_min + (center_y - zoom_nb * center_y) / 2;
	all->y_max = all->y_min + zoom_nb * center_y;
}

/* mouse_event_mgmt:
*		Input: keycode generated by mlx_mouse_hook.
*		
*		Works as an index for mouse-related events.
*		Depending on the keycode (event identifier) received, 
*		mouse_event_mgmt will decide how the program should act
*		by calling to a function or to another.
*	
*		Managed events: 
*			4 : MOUSE_WHEEL_UP
*			5 : MOUSE_WHEEL_DOWN
*/
int	mouse_event_mgmt(int keycode, t_data *all)
{
	(void)all;
	printf("MOUSE event detected: %d", keycode);
	if (keycode == MOUSE_WHEEL_UP)
	{
		printf("MOUSE WHEEL UP\n");
		ft_zoom(all->mlx, 0.5);
	}
	if (keycode == MOUSE_WHEEL_DOWN)
	{
		printf("MOUSE WHEEL down\n");
		ft_zoom(all->mlx, 2);
	}
	return (0);
}

/* key_event_mgmt:
*		Input: keycode generated by mlx_mouse_hook.
*		
*		Works as an index for keyboard-related events.
*		Depending on the keycode (event identifier) received, 
*		key_event_mgmt will decide how the program should act
*		by calling to a function or to another.
*	
*		Managed events: 
*			4 : MOUSE_WHEEL_UP
*			5 : MOUSE_WHEEL_DOWN
*/
int	key_event_mgmt(int keycode)
{
	printf("KEY event detected: %d", keycode);
	if (keycode == ESC)
		printf("ESC\n");
	if (keycode == CLOSE)
		printf("CLOSE\n");
	return (0);
}
