/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   event_handler.c                                    :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: uxmancis <uxmancis@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/01/03 17:34:46 by uxmancis          #+#    #+#             */
/*   Updated: 2024/02/04 16:24:19 by uxmancis         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "includes/fractol.h"

/* mouse_handler:
*		Input: keycode generated by mlx_mouse_hook.
*		
*		Works as an index for mouse-related events.
*		Depending on the keycode (event identifier) received, 
*		mouse_event_mgmt will decide how the program should act
*		by calling to a function or to another.
*	
*		Managed events: 
*			4 : MOUSE_WHEEL_UP (Zoom in)
*			5 : MOUSE_WHEEL_DOWN (Zoom out)
*/
int	mouse_handler(int keycode, int x, int y, t_fractal *fractal)
{
	(void)fractal;
	(void)x;
	(void)y;
	if (keycode == MOUSE_WHEEL_UP)
		fractal->zoom = fractal->zoom * 1.05;
	else if (keycode == MOUSE_WHEEL_DOWN)
		fractal->zoom = fractal->zoom * 0.95;
	ft_render(fractal);
	return (0);
}

/* key_handler:
*		Input: keycode generated by mlx_mouse_hook.
*		
*		Works as an index for keyboard-related events.
*		Depending on the keycode (event identifier) received, 
*		key_event_mgmt will decide how the program should act
*		by calling to a function or to another.
*	
*		Managed events: 
*			53 : ESC
*			123 : Key Right
*			124 : Key Left
*			125 : Key Down
*			126 : Key Up
*/
int	key_handler(int keycode, t_fractal *fractal)
{
	if (keycode == 53 || keycode == CLOSE)
	{
		close_handler(fractal);
		return (0);
	}
	if (keycode == 123)
		fractal->shift_x = fractal->shift_x - (0.5 * fractal->zoom);
	if (keycode == 124)
		fractal->shift_x = fractal->shift_x + (0.5 * fractal->zoom);
	if (keycode == DOWN)
		fractal->shift_y = fractal->shift_y + (0.5 * fractal->zoom);
	if (keycode == UP)
		fractal->shift_y = fractal->shift_y - (0.5 * fractal->zoom);
	ft_render(fractal);
	return (0);
}

/* close_handler: ESC or x (window) are pressed*/
int	close_handler(t_fractal *fractal)
{
	mlx_destroy_image(fractal->mlx_connection, fractal->img.img_ptr);
	mlx_destroy_window(fractal->mlx_connection, fractal->mlx_window);
	free(fractal->mlx_connection);
	exit(EXIT_SUCCESS);
}
