/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_fractol.c                                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: uxmancis <uxmancis@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/01/02 16:57:28 by uxmancis          #+#    #+#             */
/*   Updated: 2024/02/04 16:57:35 by uxmancis         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "includes/fractol.h"

/*ft_message
*	When arguments passed to program don't match with allowed
*	possibilities, the following message is printed.
*
*	This way, user will know in which are the possible arguments so that
*	the program can be executed.
*/
void	ft_message(void)
{
	write(1, "Non valid argument format. Allowed compillation ", 48);
	write(1, "decimals can be used on the numbers.\n", 38);
	write(1, "./fractol mandelbrot\n", 22);
	write(1, "./fractol julia <real> <imaginary>\nFor visualizing", 51);
	write(1, "Julia set, real and imaginary numbers must be between 1 and", 59);
	write(1, " -1.\nAs many decimals can be used on the numbers.\n", 50);
	write(1, " > For example: ./fractol julia -0.783 0.123\n", 45);
}

/*	ft_events_init
*	Initializes the hooks for the mlx window.
*	These hooks will be used to manage the events generated by the user.
*	These events are:
*		- Mouse wheel up / down
*		- Close button / ESC key
*/
void	ft_events_init(t_fractal *fractal)
{
	mlx_mouse_hook(fractal->mlx_window, &mouse_handler, fractal);
	mlx_hook(fractal->mlx_window, 17, (1L << 17),
		&close_handler, fractal);
	mlx_key_hook(fractal->mlx_window, &key_handler, fractal);
	mlx_hook(fractal->mlx_window, 17, 0,
		close_handler, fractal);
}

/* ft_fractal_init
*	shift_x: x axis shift (left / right)
*	shift_y: y axis shift (up / down)
*	zoom: zoom level
*/
void	ft_fractal_init(t_fractal	*fractal)
{
	double	dif_x;
	double	dif_y;

	fractal->mlx_connection = mlx_init();
	fractal->mlx_window = mlx_new_window(fractal-> mlx_connection, 500,
			500, "fract-ol uxmancis | 42 Urduliz");
	fractal->img.img_ptr = mlx_new_image(fractal->mlx_connection, 500,
			500);
	fractal->img.pixels_ptr = mlx_get_data_addr(fractal->img.img_ptr,
			&fractal->img.bpp,
			& fractal->img.line_len,
			&fractal->img.endian);
	fractal->shift_x = 0.0;
	fractal->shift_y = 0.0;
	fractal->zoom = 1.0;
	ft_events_init(fractal);
	fractal->x_min = -2;
	fractal->x_max = 2;
	fractal->y_min = -0.4;
	dif_x = fractal->x_max - fractal->x_min;
	dif_y = dif_x * HEIGHT / WIDTH;
	fractal->y_max = fractal->y_min + dif_y;
}

/* main
*	Checks if the arguments passed to the program are valid.
*	Initializes the fractal struct and calls to ft_render.
*	Finally, it starts the mlx loop.
*/
int	main(int argc, char **argv)
{
	t_fractal	fractal;

	if ((argc == 2 && ft_strcmp("mandelbrot", argv[1]) == 1)
		|| ((argc == 4 && ft_strcmp("julia", argv[1]) == 1)
			&& ft_str2double(argv[2]) >= -1 && ft_str2double(argv[2]) <= 1
			&& ft_str2double(argv[3]) >= -1 && ft_str2double(argv[3]) <= 1))
	{
		fractal.name = argv[1];
		if (argc == 4)
		{
			fractal.julia_x = ft_str2double(argv[2]);
			fractal.julia_y = ft_str2double(argv[3]);
		}
		ft_fractal_init(&fractal);
		ft_render(&fractal);
		mlx_loop(fractal.mlx_connection);
	}
	else
		ft_message();
	return (0);
}
